#!/usr/bin/env bash
#
# A Hook to enforce branch name
#
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|release|hotfix)\/[A-Za-z0-9._-]+$"

message="❌  Invalid branch name. Your branch name should start with [feature/*] as we use Git Flow on TimeKeeper"
message2="✅️ Please use the YouTrack ticket ID as part of your branch. For instance, TK-999 branch should be [feature/TK-999-short-description]"
message3="   Other valid branch names: [release/xxx] or [hotfix/xxx] branch."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    echo "$message2"
    echo "$message3"
    exit 1
fi

exit 0


