/* Replace with your SQL commands */
BEGIN ;
TRUNCATE TABLE clients RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE timeentries RESTART IDENTITY CASCADE;
TRUNCATE TABLE timesheets RESTART IDENTITY CASCADE;
TRUNCATE TABLE projects_users RESTART IDENTITY CASCADE;
TRUNCATE TABLE projects RESTART IDENTITY CASCADE;
TRUNCATE TABLE event_template RESTART IDENTITY CASCADE;
COMMIT ;