version: '3'
services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8082:8080
    volumes:
    - ./keycloak/realm-export-dev.json:/opt/jboss/keycloak/imports/realm-export.json
    - ./keycloak/themes:/opt/jboss/keycloak/themes
    command:
        - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"

  postgres:
    image: postgres:12.2
    container_name: postgres-timekeeper
    environment:
      POSTGRES_DB: timekeeper
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  mailhog-timekeeper:
    container_name: mailhog-tk
    image: mailhog/mailhog
    restart: always
    ports:
      - 1026:1025
      - 8026:8025
