DROP TABLE IF EXISTS user_events;
DROP TABLE IF EXISTS event_template;

create table event_template
(
    id bigint generated by default as identity
        constraint event_template_pkey
            primary key,
    name varchar(100) not null,
    description varchar(255),
    startdatetime timestamp,
    enddatetime timestamp,
    organization_id bigint
        constraint fk_event_orga
            references organizations
            on delete set null
);

create table user_events
(
    id bigint generated by default as identity
        constraint user_events_pkey
            primary key,
    name varchar(100) not null ,
    description varchar(255),
    startdatetime timestamp,
    enddatetime timestamp,
    eventtype varchar(50),
    eventtemplate_id bigint
        constraint fk_user_events_to_event_template
            references event_template
            on delete set null ,
    owner_id bigint
        constraint fk_user_events_to_users
            references users
            on delete set null
);


create table event_template_user_events
(
    eventtemplate_id bigint not null,
    associatedevents_id bigint not null
        constraint uk_unique_event_to_associated_event
            unique,
    constraint event_template_user_events_pkey
        primary key (eventtemplate_id, associatedevents_id)
);


