/*
 * Copyright 2020 Lunatech S.A.S
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

DROP TABLE IF EXISTS user_events;
DROP TABLE IF EXISTS event_template;

create table event_template
(
    id bigint generated by default as identity
        constraint event_template_pkey
            primary key,
    name varchar(100) not null,
    description varchar(255),
    startdatetime timestamp,
    enddatetime timestamp,
    organization_id bigint
        constraint fk_event_orga
            references organizations
            on delete set null
);

create table user_events
(
    id bigint generated by default as identity
        constraint user_events_pkey
            primary key,
    name varchar(100) not null ,
    description varchar(255),
    startdatetime timestamp,
    enddatetime timestamp,
    eventtype varchar(50),
    eventtemplate_id bigint
        constraint fk_user_events_to_event_template
            references event_template
            on delete set null ,
    owner_id bigint
        constraint fk_user_events_to_users
            references users
            on delete set null
);


create table event_template_user_events
(
    eventtemplate_id bigint not null,
    associatedevents_id bigint not null
        constraint uk_unique_event_to_associated_event
            unique,
    constraint event_template_user_events_pkey
        primary key (eventtemplate_id, associatedevents_id)
);


